### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by asmagen** [jlevy44/PathFlow-MixMatch#9]
(pytorch_p36) ubuntu:~$ pathflow-mixmatch register_images \
> --im1 data/Li63TCD20_cropped_mask.png \
> --im2 data/Li63TCD3_cropped_mask.png \
> --gpu_device 0 --transfrm_type wendland \
> --fix_rotation False --output_dir data \
> --lr 0.01 --iterations 10 --min_object_size 50000 \
> --no_segment_analysis True --black_background True
Loading images.
Performing regitration.
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/pathflow-mixmatch", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pathflow_mixmatch/cli.py", line 522, in main
    fire.Fire(Commands)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pathflow_mixmatch/cli.py", line 519, in register_images
    pyramid=pyramid)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pathflow_mixmatch/cli.py", line 448, in register_images_
    new_img=displace_image(im2,affine_register(im1, im2, gpu_device=gpu_device, lr=lr, loss_fn=loss_fn, transform_type=transform_type, iterations=iterations, opt_cm=opt_cm, sigma=sigma, order=order, pyramid=pyramid)[0],gpu_device=gpu_device) # new tri, output he as well
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pathflow_mixmatch/cli.py", line 183, in affine_register
    constant_flow = transformation.get_flow()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/airlab/transformation/pairwise.py", line 49, in get_flow
    return self._compute_flow().detach()
TypeError: 'NoneType' object is not callable

**Comment by jlevy44** [comment]
Ok, I just pushed an attempted fix

**Comment by asmagen** [comment]
Thanks, but different errors come up with either transform_type or bspline. I'll have to wait until the package debugging develops a bit more.

**Comment by jlevy44** [comment]
Ok, we'll keep debugging this, in any case, we may have a quick solution for drop2 here: #1

**Comment by jlevy44** [comment]
While this issue has been resolved, we are still working on: #1
